name: combocicdproject
on:
 pull_request:
  types:
   - closed
jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
 
