# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
 push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - run: |
        echo The PR was merged
    - name: get code
      uses: actions/checkout@v3
    - run : swift --version
    - run : ls
    - run : xcodebuild archive -scheme Githubtest -archivePath ./Build/Githubtest -configuration Release -destination 'generic/platform=iOS' -allowProvisioningUpdates
    - run : xcodebuild -exportArchive -archivePath ./Build/Githubtest.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./Build
    - uses: actions/upload-artifact@v3
      with:
       name: my-artifact
       path: Build
     
    
