# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
 push

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: get code
      uses: actions/checkout@v3
    - run: |
        echo The PR was merged
    - run : swift --version
    - run : ls      
    
